
version: '3.1'

services:
  db:
    image: mysql:5.6.47
    container_name: mysql_container
    volumes:
      - //Users/dror/db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
